alias mkdir='mkdir -p'
alias c='clear'

alias ls='ls -GFh'
alias la='ls -la'
alias ll='ls -hl'

alias sshv='bcvi --wrap-ssh -- '
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

# alias vim='mvim --remote-tab-silent'
# alias vm='mvim --remote-tab-silent || mvim'
# alias gvim='mvim --remote-tab-silent || mvim'

alias vim='mvim --remote-silent'
alias vm='mvim --remote-silent || mvim'
alias gvim='mvim --remote-silent || mvim'

alias '..'='cd ..'
alias '...'='cd ../..'
alias 'cd..'='cd ..'

#mysql
alias start_mysql='sudo /usr/local/mysql/bin/mysqld_safe &'

# git
alias gd='git diff'
alias gs='git status'
alias gc='git commit -m'
alias gA='git add -A'
alias add='git add'
alias push='git push'
alias pull='git pull'

# better navigation
# alias d='dirs -v'
# alias p='popd'
# alias cd='pushd'
