alias mkdir='mkdir -p'
alias c='clear'

alias ls='gls -GFhB --color=auto'
alias la='ls -la'
alias ll='ls -hl'

alias sshv='bcvi --wrap-ssh -- '
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'

alias vim='/Applications/MacVim.app/Contents/MacOS/Vim'
if [[ -n $TMUX ]]; then
    alias nvim='vim'
    alias vim='tmux-vim'
fi

alias '..'='cd ..'
alias '...'='cd ../..'
alias 'cd..'='cd ..'
alias ':q'='exit'

# git
alias gd='git diff'
alias gs='git status'
alias gc='git commit -m'
alias gA='git add -A'
alias add='git add'
alias push='git push'
alias pull='git pull'

alias tmux="TERM=xterm-256color tmux -u -2"

# ruby
alias be='bundle exec'
alias guard='bundle exec guard'

alias t='python ~/.bin/t --task-dir="~/notes/tasks" --list tasks'
alias tf='t -f'
alias tc='t | wc -l'
alias tree='tree -dCA -L 2'

alias fixvirtualbox='sudo chmod 755 /Applications && chmod 755 /Applications/Virtualbox.app'
