# load bashrc
if [ -f ~/.bashrc ]; then
   source ~/.bashrc
fi

[[ -s "/Users/juanolon/.rvm/scripts/rvm" ]] && source "/Users/juanolon/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
