# Skip all this for non-interactive shells
[[ -z "$PS1" ]] && return

# add android tools and mysqlbin to path
# from php53 caveats, add /usr/local/opt/php53/bin ( PATH="$(brew --prefix josegonzalez/php/php53)/bin:$PATH" )
export PATH=/usr/local/opt/php53/bin:/usr/local/bin:/usr/local/share/npm/bin:$HOME/.android/tools:$HOME/.rvm/bin:/usr/local/share/python:$HOME/.bin:$PATH

export NODE_PATH="/usr/local/share/npm/lib/node_modules"

# don't save duplicates in history
export HISTCONTROL=ignoredups:erasedups  # no duplicate entries
export HISTSIZE=9000
export HISTFILESIZE=9000
export HISTIGNORE="&:cd:ls:ll:la:lal:[bf]g:exit"
shopt -s histappend                      # append to history, don't overwrite it

# Save and reload the history after each command finishes
# this allows to share bash story amongst all the instances
# dont work yet: http://stackoverflow.com/questions/103944/real-time-history-export-amongst-bash-terminal-windows/3055135
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

export TERM=xterm-256color
export IGNOREEOF=5 # disable ctrl-d

EDITOR=vim
VISUAL=vim
PAGGER='less -i'

# set -o vi
shopt -s extglob   # extended pattern matching features
shopt -s cdspell   # correct dir spelling errors on cd
shopt -s lithist   # save multi-line commands with newlines
# shopt -s autocd    # if a command is a dir name, cd to it
# shopt -s dirspell  # correct dir spelling errors on completion
# shopt -s globstar  # ** matches all files, dirs and subdirs
shopt -s cmdhist   # save multi-line commands in a single hist entry
shopt -s checkwinsize # check the window size after each command
shopt -s no_empty_cmd_completion # don't try to complete empty cmds
shopt -s expand_aliases # expand aliases when no interactive
shopt -s histappend # append history instead of overwriting it
shopt -s nocaseglob # case-insensitive filename match

#coloured man pages
export LESS_TERMCAP_mb=$'\E[01;31m'
export LESS_TERMCAP_md=$'\E[01;31m'
export LESS_TERMCAP_me=$'\E[0m'
export LESS_TERMCAP_se=$'\E[0m'
export LESS_TERMCAP_so=$'\E[01;44;33m'
export LESS_TERMCAP_ue=$'\E[0m'
export LESS_TERMCAP_us=$'\E[01;32m'
# export LESSOPEN="|$HOME/.bash/scripts/lesspipe.sh %s"
export LESS=' -R '

#grep colors
export GREP_COLOR="1;31"
export GREP_OPTIONS='--color=auto'

__dircolors="$(type -P gdircolors dircolors | head -1)"
test -n "$__dircolors" && {
    COLORS=/etc/DIR_COLORS
    test -e "/etc/DIR_COLORS.$TERM"   && COLORS="/etc/DIR_COLORS.$TERM"
    test -e "$HOME/.dir_colors"       && COLORS="$HOME/.dir_colors"
    test ! -e "$COLORS"               && COLORS=
    eval `$__dircolors --sh "$COLORS"`
}


# file name completion ignore backups, CVS directories, python bytecode, vim swap files
FIGNORE="~:CVS:#:.pyc:.swp:.swa:apache-solr-*"

# load autocomplete, if exists
homebrew=$(brew --prefix)
if [ -f $homebrew/etc/bash_completion ]; then
    . $homebrew/etc/bash_completion
fi

for file in $(find $homebrew/etc/bash_completion.d -not -type d)
do
  source $file 2>/dev/null
done

. ~/.bash/bash_prompt
. ~/.bash/bash_aliases
. ~/.bash/bash_functions
. ~/.bash/bash_inputrc
. ~/dotfiles/bin/z.sh
source "`brew --prefix`/etc/grc.bashrc"

export LANG="en_US.UTF-8"
export LANGUAGE="en_US"
export LC_CTYPE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
